-- Consera account bootstrap
-- Required Snow CLI variables:
--   CONSERA_ADMIN_PUBLIC_KEY: unencrypted base64 DER public key body
--   CONSERA_APP_PUBLIC_KEY: unencrypted base64 DER public key body
--   CONSERA_INGEST_PUBLIC_KEY: unencrypted base64 DER public key body
--   CONSERA_ALERT_EMAIL: verified Snowflake user email
--
-- Effect: creates only CONSERA-namespaced roles, users, warehouses, database,
-- schemas, stage, and email integration. It does not alter Ripple resources.

SET CONSERA_PROVISIONER_USER = CURRENT_USER();

USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS CONSERA_INGEST_ROLE
    COMMENT = 'Consera Hacker News bridge writer';
CREATE ROLE IF NOT EXISTS CONSERA_PIPELINE_ROLE
    COMMENT = 'Consera Snowpark intelligence pipeline';
CREATE ROLE IF NOT EXISTS CONSERA_APP_ROLE
    COMMENT = 'Consera allowlisted application API';
CREATE ROLE IF NOT EXISTS CONSERA_ADMIN_ROLE
    COMMENT = 'Consera resource and release owner';

GRANT ROLE CONSERA_INGEST_ROLE TO ROLE CONSERA_ADMIN_ROLE;
GRANT ROLE CONSERA_PIPELINE_ROLE TO ROLE CONSERA_ADMIN_ROLE;
GRANT ROLE CONSERA_APP_ROLE TO ROLE CONSERA_ADMIN_ROLE;
GRANT ROLE CONSERA_ADMIN_ROLE TO ROLE SYSADMIN;
GRANT ROLE CONSERA_ADMIN_ROLE TO USER IDENTIFIER($CONSERA_PROVISIONER_USER);

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS CONSERA_INGEST_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 60
    STATEMENT_TIMEOUT_IN_SECONDS = 180
    COMMENT = 'Bounded Consera bridge ingestion';

CREATE WAREHOUSE IF NOT EXISTS CONSERA_PIPELINE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 60
    STATEMENT_TIMEOUT_IN_SECONDS = 600
    COMMENT = 'Consera deterministic and Cortex pipeline';

CREATE WAREHOUSE IF NOT EXISTS CONSERA_APP_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 60
    STATEMENT_TIMEOUT_IN_SECONDS = 180
    COMMENT = 'Consera bounded SQL API queries';

ALTER WAREHOUSE CONSERA_INGEST_WH SET
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    ENABLE_QUERY_ACCELERATION = FALSE
    STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 60
    STATEMENT_TIMEOUT_IN_SECONDS = 180;

ALTER WAREHOUSE CONSERA_PIPELINE_WH SET
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    ENABLE_QUERY_ACCELERATION = FALSE
    STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 60
    STATEMENT_TIMEOUT_IN_SECONDS = 600;

ALTER WAREHOUSE CONSERA_APP_WH SET
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    ENABLE_QUERY_ACCELERATION = FALSE
    STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 60
    STATEMENT_TIMEOUT_IN_SECONDS = 180;

CREATE DATABASE IF NOT EXISTS CONSERA
    COMMENT = 'Authoritative Consera intelligence system';

CREATE SCHEMA IF NOT EXISTS CONSERA.LANDING;
CREATE SCHEMA IF NOT EXISTS CONSERA.CORE;
CREATE SCHEMA IF NOT EXISTS CONSERA.EVIDENCE;
CREATE SCHEMA IF NOT EXISTS CONSERA.INTELLIGENCE;
CREATE SCHEMA IF NOT EXISTS CONSERA.ALERTING;
CREATE SCHEMA IF NOT EXISTS CONSERA.APP;
CREATE SCHEMA IF NOT EXISTS CONSERA.APP_API;
CREATE SCHEMA IF NOT EXISTS CONSERA.OPS;
CREATE SCHEMA IF NOT EXISTS CONSERA.SECURITY;

CREATE STAGE IF NOT EXISTS CONSERA.APP.CODE_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Versioned Consera Snowpark procedure artifacts';

GRANT OWNERSHIP ON WAREHOUSE CONSERA_INGEST_WH
    TO ROLE CONSERA_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE CONSERA_PIPELINE_WH
    TO ROLE CONSERA_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE CONSERA_APP_WH
    TO ROLE CONSERA_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE CONSERA
    TO ROLE CONSERA_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE CONSERA
    TO ROLE CONSERA_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON STAGE CONSERA.APP.CODE_STAGE
    TO ROLE CONSERA_ADMIN_ROLE COPY CURRENT GRANTS;

USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE CONSERA_INGEST_WH TO ROLE CONSERA_INGEST_ROLE;
GRANT USAGE ON WAREHOUSE CONSERA_PIPELINE_WH TO ROLE CONSERA_PIPELINE_ROLE;
GRANT USAGE ON WAREHOUSE CONSERA_APP_WH TO ROLE CONSERA_APP_ROLE;

GRANT USAGE ON DATABASE CONSERA TO ROLE CONSERA_INGEST_ROLE;
GRANT USAGE ON DATABASE CONSERA TO ROLE CONSERA_PIPELINE_ROLE;
GRANT USAGE ON DATABASE CONSERA TO ROLE CONSERA_APP_ROLE;
GRANT USAGE ON DATABASE CONSERA TO ROLE CONSERA_ADMIN_ROLE;

GRANT USAGE ON SCHEMA CONSERA.LANDING TO ROLE CONSERA_INGEST_ROLE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE CONSERA TO ROLE CONSERA_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN DATABASE CONSERA TO ROLE CONSERA_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN DATABASE CONSERA TO ROLE CONSERA_PIPELINE_ROLE;
GRANT READ ON STAGE CONSERA.APP.CODE_STAGE TO ROLE CONSERA_PIPELINE_ROLE;
GRANT WRITE ON STAGE CONSERA.APP.CODE_STAGE TO ROLE CONSERA_PIPELINE_ROLE;

GRANT USAGE ON SCHEMA CONSERA.APP_API TO ROLE CONSERA_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA CONSERA.APP_API TO ROLE CONSERA_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CONSERA.APP_API TO ROLE CONSERA_APP_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA CONSERA.APP_API TO ROLE CONSERA_APP_ROLE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA CONSERA.LANDING TO ROLE CONSERA_INGEST_ROLE;

USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS CONSERA_ADMIN_SERVICE
    TYPE = SERVICE
    RSA_PUBLIC_KEY = $CONSERA_ADMIN_PUBLIC_KEY
    DEFAULT_ROLE = CONSERA_ADMIN_ROLE
    DEFAULT_WAREHOUSE = CONSERA_PIPELINE_WH
    DEFAULT_NAMESPACE = CONSERA.APP
    COMMENT = 'Key-pair-only Consera release identity';

CREATE USER IF NOT EXISTS CONSERA_APP_SERVICE
    TYPE = SERVICE
    RSA_PUBLIC_KEY = $CONSERA_APP_PUBLIC_KEY
    DEFAULT_ROLE = CONSERA_APP_ROLE
    DEFAULT_WAREHOUSE = CONSERA_APP_WH
    DEFAULT_NAMESPACE = CONSERA.APP_API
    COMMENT = 'Key-pair-only Consera Cloudflare Worker identity';

CREATE USER IF NOT EXISTS CONSERA_INGEST_SERVICE
    TYPE = SERVICE
    RSA_PUBLIC_KEY = $CONSERA_INGEST_PUBLIC_KEY
    DEFAULT_ROLE = CONSERA_INGEST_ROLE
    DEFAULT_WAREHOUSE = CONSERA_INGEST_WH
    DEFAULT_NAMESPACE = CONSERA.LANDING
    COMMENT = 'Key-pair-only Consera Hacker News bridge identity';

ALTER USER CONSERA_ADMIN_SERVICE SET RSA_PUBLIC_KEY = $CONSERA_ADMIN_PUBLIC_KEY;
ALTER USER CONSERA_APP_SERVICE SET RSA_PUBLIC_KEY = $CONSERA_APP_PUBLIC_KEY;
ALTER USER CONSERA_INGEST_SERVICE SET RSA_PUBLIC_KEY = $CONSERA_INGEST_PUBLIC_KEY;

GRANT ROLE CONSERA_ADMIN_ROLE TO USER CONSERA_ADMIN_SERVICE;
GRANT ROLE CONSERA_APP_ROLE TO USER CONSERA_APP_SERVICE;
GRANT ROLE CONSERA_INGEST_ROLE TO USER CONSERA_INGEST_SERVICE;

USE ROLE ACCOUNTADMIN;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CONSERA_PIPELINE_ROLE;
-- noqa: disable=PRS
GRANT USE AI FUNCTION AI_COMPLETE ON ACCOUNT TO ROLE CONSERA_PIPELINE_ROLE;
-- noqa: enable=PRS
GRANT EXECUTE TASK ON ACCOUNT TO ROLE CONSERA_ADMIN_ROLE;

-- noqa: disable=PRS
CREATE RESOURCE MONITOR IF NOT EXISTS CONSERA_TRIAL_MONITOR
    WITH
        CREDIT_QUOTA = 5
        FREQUENCY = MONTHLY
        START_TIMESTAMP = IMMEDIATELY
        TRIGGERS
            ON 50 PERCENT DO NOTIFY
            ON 80 PERCENT DO SUSPEND
            ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER RESOURCE MONITOR CONSERA_TRIAL_MONITOR
    SET
        CREDIT_QUOTA = 5
        FREQUENCY = MONTHLY
        TRIGGERS
            ON 50 PERCENT DO NOTIFY
            ON 80 PERCENT DO SUSPEND
            ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE CONSERA_INGEST_WH
    SET RESOURCE_MONITOR = CONSERA_TRIAL_MONITOR;
ALTER WAREHOUSE CONSERA_PIPELINE_WH
    SET RESOURCE_MONITOR = CONSERA_TRIAL_MONITOR;
ALTER WAREHOUSE CONSERA_APP_WH
    SET RESOURCE_MONITOR = CONSERA_TRIAL_MONITOR;

GRANT MONITOR ON RESOURCE MONITOR CONSERA_TRIAL_MONITOR
    TO ROLE CONSERA_ADMIN_ROLE;
GRANT MODIFY ON RESOURCE MONITOR CONSERA_TRIAL_MONITOR
    TO ROLE CONSERA_ADMIN_ROLE;
-- noqa: enable=PRS

-- noqa: disable=PRS
CREATE NOTIFICATION INTEGRATION IF NOT EXISTS CONSERA_EMAIL_INT
    TYPE = EMAIL
    ENABLED = TRUE
    ALLOWED_RECIPIENTS = ($CONSERA_ALERT_EMAIL)
    COMMENT = 'Verified-user Consera consequence alerts';
-- noqa: enable=PRS

GRANT USAGE ON INTEGRATION CONSERA_EMAIL_INT TO ROLE CONSERA_PIPELINE_ROLE;
