-- Existing-account recovery for Consera's isolated weekly cost boundaries.
-- Run with ACCOUNTADMIN after reviewing the exact quotas and effects.
-- The retired shared monitor is left intact and becomes dormant after reassignment.

USE ROLE ACCOUNTADMIN;

-- noqa: disable=PRS
CREATE RESOURCE MONITOR IF NOT EXISTS CONSERA_INGEST_MONITOR
    WITH
        CREDIT_QUOTA = 1
        FREQUENCY = WEEKLY
        START_TIMESTAMP = IMMEDIATELY
        TRIGGERS
            ON 60 PERCENT DO NOTIFY
            ON 85 PERCENT DO SUSPEND
            ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE RESOURCE MONITOR IF NOT EXISTS CONSERA_PIPELINE_MONITOR
    WITH
        CREDIT_QUOTA = 2
        FREQUENCY = WEEKLY
        START_TIMESTAMP = IMMEDIATELY
        TRIGGERS
            ON 60 PERCENT DO NOTIFY
            ON 85 PERCENT DO SUSPEND
            ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE RESOURCE MONITOR IF NOT EXISTS CONSERA_APP_MONITOR
    WITH
        CREDIT_QUOTA = 1
        FREQUENCY = WEEKLY
        START_TIMESTAMP = IMMEDIATELY
        TRIGGERS
            ON 60 PERCENT DO NOTIFY
            ON 85 PERCENT DO SUSPEND
            ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER RESOURCE MONITOR CONSERA_INGEST_MONITOR
    SET
        CREDIT_QUOTA = 1
        TRIGGERS
            ON 60 PERCENT DO NOTIFY
            ON 85 PERCENT DO SUSPEND
            ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER RESOURCE MONITOR CONSERA_PIPELINE_MONITOR
    SET
        CREDIT_QUOTA = 2
        TRIGGERS
            ON 60 PERCENT DO NOTIFY
            ON 85 PERCENT DO SUSPEND
            ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER RESOURCE MONITOR CONSERA_APP_MONITOR
    SET
        CREDIT_QUOTA = 1
        TRIGGERS
            ON 60 PERCENT DO NOTIFY
            ON 85 PERCENT DO SUSPEND
            ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE CONSERA_INGEST_WH
    SET RESOURCE_MONITOR = CONSERA_INGEST_MONITOR;
ALTER WAREHOUSE CONSERA_PIPELINE_WH
    SET RESOURCE_MONITOR = CONSERA_PIPELINE_MONITOR;
ALTER WAREHOUSE CONSERA_APP_WH
    SET RESOURCE_MONITOR = CONSERA_APP_MONITOR;

GRANT MONITOR, MODIFY ON RESOURCE MONITOR CONSERA_INGEST_MONITOR
    TO ROLE CONSERA_ADMIN_ROLE;
GRANT MONITOR, MODIFY ON RESOURCE MONITOR CONSERA_PIPELINE_MONITOR
    TO ROLE CONSERA_ADMIN_ROLE;
GRANT MONITOR, MODIFY ON RESOURCE MONITOR CONSERA_APP_MONITOR
    TO ROLE CONSERA_ADMIN_ROLE;
-- noqa: enable=PRS

USE ROLE CONSERA_ADMIN_ROLE;

ALTER WAREHOUSE CONSERA_INGEST_WH SET
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    ENABLE_QUERY_ACCELERATION = FALSE;

ALTER WAREHOUSE CONSERA_PIPELINE_WH SET
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    ENABLE_QUERY_ACCELERATION = FALSE;

ALTER WAREHOUSE CONSERA_APP_WH SET
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    ENABLE_QUERY_ACCELERATION = FALSE;
