USE ROLE CONSERA_ADMIN_ROLE;
USE DATABASE CONSERA;

ALTER TASK APP.PROCESS_PROFILE_TASK RESUME;
ALTER TASK APP.PROCESS_LANDING_TASK RESUME;
ALTER TASK APP.PROCESS_EVALUATION_TASK RESUME;
ALTER TASK APP.PROCESS_ALERT_TASK RESUME;
