USE ROLE CONSERA_ADMIN_ROLE;
USE WAREHOUSE CONSERA_PIPELINE_WH;
USE DATABASE CONSERA;

CREATE TABLE IF NOT EXISTS CORE.PROJECTS (
    PROJECT_ID VARCHAR(64) NOT NULL,
    OWNER_USER_NAME VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(200) NOT NULL,
    SLUG VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(2000),
    STATE VARCHAR(32) NOT NULL,
    ACTIVE_PROFILE_VERSION_ID VARCHAR(64),
    ALERT_EMAIL VARCHAR(320),
    ALERTS_ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    ROW_VERSION NUMBER(38, 0) NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    UPDATED_AT TIMESTAMP_TZ NOT NULL,
    ARCHIVED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS CORE.PROJECT_DOCUMENTS (
    DOCUMENT_ID VARCHAR(64) NOT NULL,
    PROJECT_ID VARCHAR(64) NOT NULL,
    DOCUMENT_TYPE VARCHAR(32) NOT NULL,
    SOURCE_NAME VARCHAR(500) NOT NULL,
    SOURCE_URI VARCHAR(2000),
    CONTENT_SHA256 VARCHAR(64) NOT NULL,
    SANITIZED_CONTENT VARCHAR(200000) NOT NULL,
    BYTE_LENGTH NUMBER(38, 0) NOT NULL,
    SECRET_SCAN_STATUS VARCHAR(32) NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL,
    RETAIN_UNTIL TIMESTAMP_TZ,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS CORE.PROJECT_PROFILE_VERSIONS (
    PROFILE_VERSION_ID VARCHAR(64) NOT NULL,
    PROJECT_ID VARCHAR(64) NOT NULL,
    SOURCE_DOCUMENT_ID VARCHAR(64) NOT NULL,
    EXTRACTOR_VERSION VARCHAR(64) NOT NULL,
    PROFILE_SCHEMA_VERSION NUMBER(10, 0) NOT NULL,
    PROFILE_NUMBER NUMBER(38, 0) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    PRODUCT_SUMMARY VARCHAR(5000) NOT NULL,
    TARGET_USERS ARRAY NOT NULL,
    CORE_CAPABILITIES ARRAY NOT NULL,
    DEPENDENCIES ARRAY NOT NULL,
    PROVIDERS ARRAY NOT NULL,
    MODELS ARRAY NOT NULL,
    FRAMEWORKS ARRAY NOT NULL,
    COMPETITORS ARRAY NOT NULL,
    DIFFERENTIATORS ARRAY NOT NULL,
    CONSTRAINTS ARRAY NOT NULL,
    BUSINESS_MODEL VARIANT,
    PRIORITIES ARRAY NOT NULL,
    RISK_SENSITIVITIES ARRAY NOT NULL,
    MONITORED_TOPICS ARRAY NOT NULL,
    UNRESOLVED_QUESTIONS ARRAY NOT NULL,
    COMPLETENESS_SCORE NUMBER(6, 5) NOT NULL,
    CONFIDENCE_SCORE NUMBER(6, 5) NOT NULL,
    PROFILE_HASH VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    REVIEWED_AT TIMESTAMP_TZ,
    ACTIVATED_AT TIMESTAMP_TZ,
    REVIEWED_BY VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CORE.PROJECT_PROFILE_CORRECTIONS (
    CORRECTION_ID VARCHAR(64) NOT NULL,
    PROFILE_VERSION_ID VARCHAR(64) NOT NULL,
    FIELD_PATH VARCHAR(500) NOT NULL,
    BEFORE_VALUE VARIANT,
    AFTER_VALUE VARIANT,
    REASON VARCHAR(1000),
    ACTOR_USER_NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS LANDING.INGEST_BATCHES (
    BATCH_ID VARCHAR(64) NOT NULL,
    SOURCE VARCHAR(64) NOT NULL,
    FETCH_MODE VARCHAR(32) NOT NULL,
    FETCH_STARTED_AT TIMESTAMP_TZ NOT NULL,
    FETCH_COMPLETED_AT TIMESTAMP_TZ NOT NULL,
    ITEM_COUNT NUMBER(10, 0) NOT NULL,
    PAYLOAD_SHA256 VARCHAR(64) NOT NULL,
    BRIDGE_VERSION VARCHAR(64) NOT NULL,
    GITHUB_RUN_ID VARCHAR(100),
    INGESTED_AT TIMESTAMP_TZ NOT NULL,
    VALIDATION_STATUS VARCHAR(32) NOT NULL,
    ERROR_CODE VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS LANDING.HN_ITEMS_RAW (
    BATCH_ID VARCHAR(64) NOT NULL,
    HN_ITEM_ID NUMBER(38, 0) NOT NULL,
    ITEM_TYPE VARCHAR(32) NOT NULL,
    PAYLOAD VARIANT NOT NULL,
    PAYLOAD_SHA256 VARCHAR(64) NOT NULL,
    FETCHED_AT TIMESTAMP_TZ NOT NULL,
    BRIDGE_VERSION VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS CORE.SIGNALS (
    SIGNAL_ID VARCHAR(64) NOT NULL,
    SOURCE VARCHAR(64) NOT NULL,
    SOURCE_ITEM_ID VARCHAR(128) NOT NULL,
    CURRENT_VERSION_ID VARCHAR(64) NOT NULL,
    TITLE VARCHAR(1000) NOT NULL,
    CANONICAL_URL VARCHAR(4000),
    HN_URL VARCHAR(4000) NOT NULL,
    AUTHOR VARCHAR(255),
    FIRST_SEEN_AT TIMESTAMP_TZ NOT NULL,
    LAST_SEEN_AT TIMESTAMP_TZ NOT NULL,
    CURRENT_SCORE NUMBER(10, 0),
    CURRENT_COMMENT_COUNT NUMBER(10, 0),
    SIGNAL_STATE VARCHAR(32) NOT NULL,
    TOPIC_LABELS ARRAY NOT NULL,
    PRIMARY_DOMAIN VARCHAR(255),
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    IS_DEAD BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS CORE.SIGNAL_VERSIONS (
    SIGNAL_VERSION_ID VARCHAR(64) NOT NULL,
    SIGNAL_ID VARCHAR(64) NOT NULL,
    SOURCE_PAYLOAD_SHA256 VARCHAR(64) NOT NULL,
    TITLE VARCHAR(1000) NOT NULL,
    URL VARCHAR(4000),
    STORY_TEXT VARCHAR(20000),
    SCORE NUMBER(10, 0),
    COMMENT_COUNT NUMBER(10, 0),
    TOP_COMMENT_IDS ARRAY NOT NULL,
    NORMALIZED_TEXT VARCHAR(30000) NOT NULL,
    NORMALIZED_TEXT_SHA256 VARCHAR(64) NOT NULL,
    OBSERVED_AT TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS CORE.HN_COMMENTS (
    COMMENT_VERSION_ID VARCHAR(64) NOT NULL,
    COMMENT_ID NUMBER(38, 0) NOT NULL,
    SIGNAL_ID VARCHAR(64) NOT NULL,
    PARENT_ID NUMBER(38, 0),
    AUTHOR VARCHAR(255),
    DEPTH NUMBER(5, 0) NOT NULL,
    SANITIZED_TEXT VARCHAR(12000),
    TEXT_SHA256 VARCHAR(64),
    SCORE_PROXY NUMBER(10, 0),
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    IS_DEAD BOOLEAN NOT NULL DEFAULT FALSE,
    OBSERVED_AT TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS EVIDENCE.EVIDENCE_ITEMS (
    EVIDENCE_ID VARCHAR(64) NOT NULL,
    PROJECT_ID VARCHAR(64),
    SIGNAL_ID VARCHAR(64),
    SIGNAL_VERSION_ID VARCHAR(64),
    KIND VARCHAR(32) NOT NULL,
    SOURCE_URI VARCHAR(4000),
    SOURCE_ITEM_ID VARCHAR(128),
    EXCERPT_TEXT VARCHAR(1200) NOT NULL,
    EXCERPT_SHA256 VARCHAR(64) NOT NULL,
    CONTEXT_LABEL VARCHAR(500),
    OBSERVED_AT TIMESTAMP_TZ NOT NULL,
    RETAIN_UNTIL TIMESTAMP_TZ NOT NULL,
    RETRACTED_AT TIMESTAMP_TZ,
    RETRACTION_REASON VARCHAR(1000),
    CREATED_AT TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS OPS.EVALUATION_JOBS (
    JOB_ID VARCHAR(64) NOT NULL,
    PROJECT_ID VARCHAR(64) NOT NULL,
    PROFILE_VERSION_ID VARCHAR(64) NOT NULL,
    SIGNAL_ID VARCHAR(64) NOT NULL,
    SIGNAL_VERSION_ID VARCHAR(64) NOT NULL,
    PIPELINE_VERSION VARCHAR(64) NOT NULL,
    INPUT_HASH VARCHAR(64) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    CLAIM_COUNT NUMBER(10, 0) NOT NULL DEFAULT 0,
    PROVIDER_ATTEMPT_COUNT NUMBER(10, 0) NOT NULL DEFAULT 0,
    BUDGET_DEFERRAL_COUNT NUMBER(10, 0) NOT NULL DEFAULT 0,
    MAX_PROVIDER_ATTEMPTS NUMBER(10, 0) NOT NULL DEFAULT 3,
    LEASE_OWNER VARCHAR(255),
    LEASE_TOKEN VARCHAR(64),
    LEASE_GENERATION NUMBER(38, 0) NOT NULL DEFAULT 0,
    LEASE_EXPIRES_AT TIMESTAMP_TZ,
    HEARTBEAT_AT TIMESTAMP_TZ,
    NEXT_ATTEMPT_AT TIMESTAMP_TZ NOT NULL,
    LAST_ERROR_CODE VARCHAR(100),
    LAST_ERROR_DETAIL VARCHAR(2000),
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    UPDATED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS INTELLIGENCE.VERDICTS (
    VERDICT_ID VARCHAR(64) NOT NULL,
    JOB_ID VARCHAR(64) NOT NULL,
    PROJECT_ID VARCHAR(64) NOT NULL,
    PROFILE_VERSION_ID VARCHAR(64) NOT NULL,
    SIGNAL_ID VARCHAR(64) NOT NULL,
    SIGNAL_VERSION_ID VARCHAR(64) NOT NULL,
    VERDICT_TYPE VARCHAR(64) NOT NULL,
    IMPACT_TYPE VARCHAR(64) NOT NULL,
    RELEVANCE_SCORE NUMBER(6, 5) NOT NULL,
    OPPORTUNITY_SCORE NUMBER(6, 5) NOT NULL,
    THREAT_SCORE NUMBER(6, 5) NOT NULL,
    REPLACEMENT_PRESSURE_SCORE NUMBER(6, 5) NOT NULL,
    DEPENDENCY_IMPACT_SCORE NUMBER(6, 5) NOT NULL,
    IMPACT_PEAK_SCORE NUMBER(6, 5) NOT NULL,
    URGENCY_SCORE NUMBER(6, 5) NOT NULL,
    CONFIDENCE_SCORE NUMBER(6, 5) NOT NULL,
    ALERT_WORTHINESS_SCORE NUMBER(6, 5) NOT NULL,
    HEADLINE VARCHAR(500) NOT NULL,
    WHAT_HAPPENED VARCHAR(5000) NOT NULL,
    WHY_IT_MATTERS VARCHAR(7000) NOT NULL,
    VERDICT_SUMMARY VARCHAR(5000) NOT NULL,
    UNCERTAINTY VARCHAR(2000) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    MODEL_ID VARCHAR(255) NOT NULL,
    PROMPT_VERSION VARCHAR(64) NOT NULL,
    FORMULA_VERSION VARCHAR(64) NOT NULL,
    VERDICT_SCHEMA_VERSION NUMBER(10, 0) NOT NULL,
    INPUT_HASH VARCHAR(64) NOT NULL,
    OUTPUT_SHA256 VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    PUBLISHED_AT TIMESTAMP_TZ,
    STALE_AT TIMESTAMP_TZ,
    STALE_REASON VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS INTELLIGENCE.VERDICT_COMPONENTS (
    VERDICT_ID VARCHAR(64) NOT NULL,
    COMPONENT_TYPE VARCHAR(64) NOT NULL,
    RAW_SCORE NUMBER(6, 5) NOT NULL,
    EXPLANATION VARCHAR(3000) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS INTELLIGENCE.SCORE_CONTRIBUTIONS (
    VERDICT_ID VARCHAR(64) NOT NULL,
    SCORE_TYPE VARCHAR(64) NOT NULL,
    COMPONENT_TYPE VARCHAR(64) NOT NULL,
    WEIGHT NUMBER(6, 5) NOT NULL,
    CONTRIBUTION NUMBER(6, 5) NOT NULL,
    FORMULA_VERSION VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS INTELLIGENCE.VERDICT_EVIDENCE_LINKS (
    VERDICT_ID VARCHAR(64) NOT NULL,
    EVIDENCE_ID VARCHAR(64) NOT NULL,
    CLAIM_KEY VARCHAR(128) NOT NULL,
    SUPPORT_TYPE VARCHAR(32) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS INTELLIGENCE.RECOMMENDATIONS (
    RECOMMENDATION_ID VARCHAR(64) NOT NULL,
    VERDICT_ID VARCHAR(64) NOT NULL,
    ORDINAL NUMBER(5, 0) NOT NULL,
    ACTION_TYPE VARCHAR(64) NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    RATIONALE VARCHAR(3000) NOT NULL,
    EFFORT VARCHAR(16) NOT NULL,
    TIME_HORIZON VARCHAR(32) NOT NULL,
    EVIDENCE_IDS ARRAY NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS INTELLIGENCE.PROTECTIVE_FACTORS (
    PROTECTIVE_FACTOR_ID VARCHAR(64) NOT NULL,
    VERDICT_ID VARCHAR(64) NOT NULL,
    ORDINAL NUMBER(5, 0) NOT NULL,
    FACTOR VARCHAR(1000) NOT NULL,
    STRENGTH NUMBER(6, 5) NOT NULL,
    EVIDENCE_IDS ARRAY NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS ALERTING.ALERT_DECISIONS (
    ALERT_ID VARCHAR(64) NOT NULL,
    PROJECT_ID VARCHAR(64) NOT NULL,
    VERDICT_ID VARCHAR(64) NOT NULL,
    POLICY_VERSION VARCHAR(64) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    RECIPIENT VARCHAR(320),
    SUPPRESSION_REASON VARCHAR(500),
    MATERIALITY_SCORE NUMBER(6, 5) NOT NULL,
    DEDUPE_KEY VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    QUEUED_AT TIMESTAMP_TZ,
    SENT_AT TIMESTAMP_TZ,
    ACKNOWLEDGED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS ALERTING.NOTIFICATION_DELIVERIES (
    DELIVERY_ID VARCHAR(64) NOT NULL,
    ALERT_ID VARCHAR(64) NOT NULL,
    CHANNEL VARCHAR(32) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    ATTEMPT_COUNT NUMBER(10, 0) NOT NULL DEFAULT 0,
    NEXT_ATTEMPT_AT TIMESTAMP_TZ,
    PROVIDER_MESSAGE_ID VARCHAR(500),
    LAST_ERROR_CODE VARCHAR(100),
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    UPDATED_AT TIMESTAMP_TZ NOT NULL
);

CREATE TABLE IF NOT EXISTS OPS.AI_USAGE_LEDGER (
    USAGE_ID VARCHAR(64) NOT NULL,
    USAGE_DATE DATE NOT NULL,
    OPERATION_TYPE VARCHAR(64) NOT NULL,
    MODEL_ID VARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(64),
    JOB_ID VARCHAR(64),
    REQUEST_HASH VARCHAR(64) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    RESERVED_INPUT_TOKENS NUMBER(38, 0) NOT NULL,
    RESERVED_OUTPUT_TOKENS NUMBER(38, 0) NOT NULL,
    ACTUAL_INPUT_TOKENS NUMBER(38, 0),
    ACTUAL_OUTPUT_TOKENS NUMBER(38, 0),
    ESTIMATED_CREDITS NUMBER(18, 8),
    REQUESTED_AT TIMESTAMP_TZ NOT NULL,
    RECONCILED_AT TIMESTAMP_TZ,
    AMBIGUOUS_CHARGE BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS OPS.PIPELINE_RUNS (
    RUN_ID VARCHAR(64) NOT NULL,
    RUN_TYPE VARCHAR(64) NOT NULL,
    ROOT_TASK_NAME VARCHAR(500),
    SCHEDULED_TIME TIMESTAMP_TZ,
    STARTED_AT TIMESTAMP_TZ,
    COMPLETED_AT TIMESTAMP_TZ,
    STATE VARCHAR(32) NOT NULL,
    INPUT_COUNT NUMBER(38, 0) NOT NULL DEFAULT 0,
    OUTPUT_COUNT NUMBER(38, 0) NOT NULL DEFAULT 0,
    ERROR_COUNT NUMBER(38, 0) NOT NULL DEFAULT 0,
    CREDIT_ESTIMATE NUMBER(18, 8),
    ERROR_SUMMARY VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS OPS.AUDIT_FINDINGS (
    FINDING_ID VARCHAR(64) NOT NULL,
    AUDIT_NAME VARCHAR(255) NOT NULL,
    SEVERITY VARCHAR(16) NOT NULL,
    ENTITY_TYPE VARCHAR(64) NOT NULL,
    ENTITY_ID VARCHAR(128),
    DETAILS VARIANT NOT NULL,
    DETECTED_AT TIMESTAMP_TZ NOT NULL,
    RESOLVED_AT TIMESTAMP_TZ,
    RESOLUTION VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS OPS.IDEMPOTENCY_KEYS (
    OPERATION VARCHAR(64) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(64) NOT NULL,
    REQUEST_HASH VARCHAR(64) NOT NULL,
    RESPONSE VARIANT,
    STATE VARCHAR(32) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS OPS.MANUAL_INGESTION_REQUESTS (
    RUN_ID VARCHAR(64) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(64) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    REQUESTED_AT TIMESTAMP_TZ NOT NULL,
    CLAIMED_AT TIMESTAMP_TZ,
    COMPLETED_AT TIMESTAMP_TZ,
    BATCH_ID VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS OPS.BATCH_WORK_QUEUE (
    BATCH_ID VARCHAR(64) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    ENQUEUED_AT TIMESTAMP_TZ NOT NULL,
    STARTED_AT TIMESTAMP_TZ,
    COMPLETED_AT TIMESTAMP_TZ,
    LAST_ERROR_CODE VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS OPS.PROFILE_WORK_QUEUE (
    PROJECT_ID VARCHAR(64) NOT NULL,
    DOCUMENT_ID VARCHAR(64) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    ENQUEUED_AT TIMESTAMP_TZ NOT NULL,
    STARTED_AT TIMESTAMP_TZ,
    COMPLETED_AT TIMESTAMP_TZ,
    LAST_ERROR_CODE VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS OPS.PIPELINE_CONFIG (
    CONFIG_KEY VARCHAR(128) NOT NULL,
    CONFIG_VALUE VARIANT NOT NULL,
    UPDATED_AT TIMESTAMP_TZ NOT NULL,
    UPDATED_BY VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS OPS.ACTIVITY_LOG (
    ACTIVITY_ID VARCHAR(64) NOT NULL,
    TITLE VARCHAR(160) NOT NULL,
    DETAIL VARCHAR(300) NOT NULL,
    STATE VARCHAR(32) NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    ENTITY_TYPE VARCHAR(64),
    ENTITY_ID VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS SECURITY.AUDIT_CHAIN (
    EVENT_ID VARCHAR(64) NOT NULL,
    SEQUENCE_NUMBER NUMBER(38, 0) NOT NULL,
    EVENT_TYPE VARCHAR(128) NOT NULL,
    ENTITY_TYPE VARCHAR(64) NOT NULL,
    ENTITY_ID VARCHAR(128) NOT NULL,
    EVENT_HASH VARCHAR(64) NOT NULL,
    PREVIOUS_HASH VARCHAR(64) NOT NULL,
    EVENT_PAYLOAD VARIANT NOT NULL,
    ACTOR VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL
);

MERGE INTO OPS.PIPELINE_CONFIG AS target
USING (
    SELECT
        column1 AS CONFIG_KEY,
        PARSE_JSON(column2) AS CONFIG_VALUE
    FROM VALUES
        ('formula_version', '"impact-formula-v1"'),
        ('alert_policy_version', '"alert-policy-v1"'),
        ('pipeline_version', '"consera-pipeline-v1"'),
        ('daily_ai_credit_limit', '2'),
        ('account_credit_envelope', '320'),
        ('account_credit_reserve', '80'),
        ('max_deep_analyses_per_batch', '12'),
        ('max_email_alerts_per_project_day', '3'),
        ('max_email_alerts_per_account_day', '5'),
        ('model_schema_reliability', '0.95'),
        ('alert_email', 'null'),
        ('selected_model', 'null')
) AS source
    ON target.CONFIG_KEY = source.CONFIG_KEY
WHEN NOT MATCHED THEN
    INSERT (CONFIG_KEY, CONFIG_VALUE, UPDATED_AT, UPDATED_BY)
    VALUES (source.CONFIG_KEY, source.CONFIG_VALUE, CURRENT_TIMESTAMP(), CURRENT_USER());
