USE ROLE CONSERA_ADMIN_ROLE;
USE WAREHOUSE CONSERA_PIPELINE_WH;
USE DATABASE CONSERA;

CREATE OR REPLACE PROCEDURE APP.PROCESS_EVALUATION_QUEUE()
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python', 'pydantic')
IMPORTS = ('@APP.CODE_STAGE/consera_runtime.zip')
HANDLER = 'intelligence.process_evaluation_queue'
EXECUTE AS OWNER;

CREATE OR REPLACE PROCEDURE APP.PROCESS_ALERT_QUEUE()
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python')
IMPORTS = ('@APP.CODE_STAGE/consera_runtime.zip')
HANDLER = 'delivery.deliver_alert_queue'
EXECUTE AS OWNER;

CREATE OR REPLACE PROCEDURE APP_API.ASK_CONSERA(
    PROJECT_IDS ARRAY,
    QUESTION VARCHAR,
    IDEMPOTENCY_KEY VARCHAR
)
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python', 'pydantic')
IMPORTS = ('@APP.CODE_STAGE/consera_runtime.zip')
HANDLER = 'intelligence.ask_consera'
EXECUTE AS OWNER;

CREATE STREAM IF NOT EXISTS OPS.EVALUATION_JOB_STREAM
    ON TABLE OPS.EVALUATION_JOBS;

CREATE STREAM IF NOT EXISTS ALERTING.ALERT_DECISION_STREAM
    ON TABLE ALERTING.ALERT_DECISIONS;

CREATE OR REPLACE TASK APP.PROCESS_PROFILE_TASK
    WAREHOUSE = CONSERA_PIPELINE_WH
    USER_TASK_TIMEOUT_MS = 180000
    SUSPEND_TASK_AFTER_NUM_FAILURES = 3
    WHEN SYSTEM$STREAM_HAS_DATA ('CONSERA.CORE.PROJECT_DOCUMENT_STREAM')
    AS CALL APP.PROCESS_PROFILE_QUEUE();

CREATE OR REPLACE TASK APP.PROCESS_LANDING_TASK
    WAREHOUSE = CONSERA_PIPELINE_WH
    USER_TASK_TIMEOUT_MS = 240000
    SUSPEND_TASK_AFTER_NUM_FAILURES = 3
    WHEN SYSTEM$STREAM_HAS_DATA ('CONSERA.LANDING.INGEST_BATCH_STREAM')
    AS CALL APP.PROCESS_LANDING_QUEUE();

CREATE OR REPLACE TASK APP.PROCESS_EVALUATION_TASK
    WAREHOUSE = CONSERA_PIPELINE_WH
    USER_TASK_TIMEOUT_MS = 600000
    SUSPEND_TASK_AFTER_NUM_FAILURES = 3
    WHEN SYSTEM$STREAM_HAS_DATA ('CONSERA.OPS.EVALUATION_JOB_STREAM')
    AS CALL APP.PROCESS_EVALUATION_QUEUE();

CREATE OR REPLACE TASK APP.PROCESS_ALERT_TASK
    WAREHOUSE = CONSERA_PIPELINE_WH
    USER_TASK_TIMEOUT_MS = 180000
    SUSPEND_TASK_AFTER_NUM_FAILURES = 1
    WHEN SYSTEM$STREAM_HAS_DATA ('CONSERA.ALERTING.ALERT_DECISION_STREAM')
    AS CALL APP.PROCESS_ALERT_QUEUE();

GRANT USAGE ON PROCEDURE APP_API.ASK_CONSERA(
    ARRAY,
    VARCHAR,
    VARCHAR
) TO ROLE CONSERA_APP_ROLE;
