USE ROLE CONSERA_ADMIN_ROLE;
USE WAREHOUSE CONSERA_PIPELINE_WH;
USE DATABASE CONSERA;

-- Make the independent profile task's cost and retry behavior as explicit as the ingestion graph.
ALTER TASK IF EXISTS APP.PROCESS_PROFILE_TASK SUSPEND;

-- noqa: disable=PRS
CREATE OR REPLACE TASK APP.PROCESS_PROFILE_TASK
    WAREHOUSE = CONSERA_PIPELINE_WH
    USER_TASK_TIMEOUT_MS = 180000
    SUSPEND_TASK_AFTER_NUM_FAILURES = 2
    TASK_AUTO_RETRY_ATTEMPTS = 0
    OVERLAP_POLICY = NO_OVERLAP
    WHEN SYSTEM$STREAM_HAS_DATA ('CONSERA.CORE.PROJECT_DOCUMENT_STREAM')
    AS CALL APP.PROCESS_PROFILE_QUEUE();
-- noqa: enable=PRS

ALTER TASK APP.PROCESS_PROFILE_TASK RESUME;
